import type { Metadata } from "next";
import { Inter, Aladin } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-inter",
});

const aladin = Aladin({
  weight: ["400"],
  variable: "--font-aladin",
});

export const metadata: Metadata = {
  title: "TripNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${aladin.variable} font-inter showScrollbar`}>
        {children}
      </body>
    </html>
  );
}
